package modelo;
/**
 * Enumeracion de los distritos de Madrid.
 * 
 * @author Elena Cano
 * @author Pablo Izaguirre
 * @author Miguel Escribano
 */

public enum Distrito {
   ARGANZUELA,BARAJAS,CARABANCHEL,CENTRO,CHAMARTIN,CHAMBERI,CIUDADLINEAL,
   FUENCARRALELPARDO,HORTALEZA,LATINA,MONCLOAARAVACA,MORATALAZ,PUENTEVALLECAS,
   RETIRO,SALAMANCA,SANBLASCANILLEJAS,TETUAN,USERA,VICALVARO,VILLAVALLECAS,VILLAVERDE; 
}